accounts/urls.py
from django.conf.urls import url
from . import views as accounts_views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/', accounts_views.register, name='register'),
    url(r'^login/', accounts_views.login_user, name='login'),
    url(r'^logout/', accounts_views.logout_user, name='logout'),
]

main/urls.py
from django.conf.urls import url
from . import views as main_views

app_name = 'main'

urlpatterns = [
    url(r'^$', main_views.home, name='home'),
    url(r'^details/ (?P<id>\d+)/', main_views.detail, name="detail"),
    url(r'^addprojects/', main_views.add_projects, name="add_projects"),
    url(r'^editprojects/(?P<id>\d+)/', main_views.edit_projects, name="edit_projects"),
    url(r'^deleteprojects/(?P<id>\d+)/', main_views.delete_projects, name="delete_projects"),
    url(r'^addreview/(?P<id>\d+)/', main_views.add_review, name="add_review"),
    url(r'^editreview/(?P<project_id>\d+)/(?P<review_id>\d+)/', main_views.edit_review, name="edit_review"),
    # url(r'^deletereview/<int:project_id>/<int:review_id/', main_views.delete_review, name="delete_review"),
]

projectreview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Project(models.Model):
    # fields for the project table
    name = models.CharField(max_length=300)
    image = models.ImageField(blank=True, null=True)
    reviewDate = models.DateTimeField(default=timezone.now())
    languages = models.CharField(max_length=300)
    description = models.TextField(max_length=5000)
    projectLink = models.CharField(max_length=300)
    averageRating = models.FloatField(default=0)

    def __str__(self):
        return self.name

class Review(models.Model):
    # fields for the review table
    #project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username
 

main/forms.py
from django import forms
from .models import *

# Project add form
class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            'name',
            'image',
            'languages',
            'description',
            'projectLink'
            ]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'rating']

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def home(request):
    query = request.GET.get('title')
    allProjects = None
    if query:
        allProjects = Project.objects.filter(name__icontains=query)
    else:
        allProjects = Project.objects.all() # selects everything from the Project table
    
    context = {
        'projects' : allProjects,
    }
    return render(request, 'main/index.html', context)

# detail page
def detail(request, id):
    project = Project.objects.get(id=id) # Selects everything from the Project table where id=id
    reviews = Review.objects.filter(comment=id).order_by('-comment')

    context = {
        "project" : project,
        "reviews" : reviews,
    }
    return render(request, 'main/details.html', context)

# add projects to the database
def add_projects(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST or None)

        # check if form is valid
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('main:home')
    else:
        form = ProjectForm()
    return render(request, 'main/addprojects.html', {"form":form, "controller":"Add Project"})

# edit the project
def edit_projects(request, id):
    # get the projects linked with id
    project = Project.objects.get(id=id)

    # form check
    if request.method == 'POST':
        form = ProjectForm(request.POST or None, instance=project)
        # check if form is valid
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('main:detail', id)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'main/addprojects.html', {"form":form, "controller":"Edit Project"})

# delete project
def delete_projects(request, id):
    # get the project by id
    project = Project.objects.get(id=id)

    # delete the project
    project.delete()
    return redirect("main:home")

# the reviews view
def add_review(request, id):
    if request.user.is_authenticated:
        project = Project.objects.get(id=id)
        if request.method == 'POST':
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST['comment']
                data.rating = request.POST['rating']
                data.user = request.user
                # data.project = project
                data.save()
                return redirect('main:detail', id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form":form})
    else:
        return redirect('accounts:login')

# edit reviews
def edit_review(request, project_id, review_id):
    if request.user.is_authenticated:
        project = Project.objects.get(id=project_id)
        review = Review.objects.get(project=project, id=review_id)

        # check if the review was done by a logged in user
        if request.user == review.user:
            # grant permissioon
            if request.method == 'POST':
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = 'Out of range. Please select rating from 0 to 10'
                        return render(request, 'main/editreview.html', {"error":error})
                    else:
                        data.save()
                        return redirect('main:detail', project_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {"form":form})
        else:
            return redirect('main:detail', project_id)
    else:
        return redirect('accounts:login')

# delete review
def delete_review(request, project_id, review_id):
    if request.user.is_authenticated:
        project = Project.objects.get(id=project_id)
        review = Review.objects.get(project=project, id=review_id)

        # check if the review was done by a logged in user
        if request.user == review.user:
            # grant permission
            review.delete()
    else:
        return redirect('accounts:login')

main/templates/main/addprojects.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="card" style="padding: 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold;">
            <div class="card-content">
                <h3 class="text-center">{{ controller }}</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="{{ controller }}" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
  {% bootstrap_css %}
    
    <title>Awards</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home' %}" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: 600; font-size: 28px;">Awards</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto" style="font-family: monospace; font-size: 18px;">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add_projects' %}">Add Projects</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">My Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
              </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}" style="font-family: monospace; font-size: 18px;">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      </br>

    {% block content %}

    {% endblock %}
    </br>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ project.image.url }}" alt="{{ project.name }}" class="img-fluid">
                </div>
                <div class="col-md-8" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold;">
                    <h3 class="text-center" style="font-family: monospace; font-weight: bold; text-decoration-line: underline; text-decoration-color: crimson;">{{ project.name }}</h3>
                    <p class="text-center" style="font-style: italic; font-weight: bold;">{{ project.description }}</p>
                    <h5>Languages: {{ project.languages }}</h5>
                    <h5>Rating: {{ project.averageRating }}</h5>
                    <h5>Visit Project: <a href="{{ project.projectLink }}" target="_blank">{{ project.name }}</a></h5>
                
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'main:edit_projects' project.id %}" class=" btn btn-warning">Edit</a>
                            <a href="{% url 'main:delete_projects' project.id %}" class=" btn btn-danger"  onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'main:add_review' project.id %}" method="POST">
                {% csrf_token %}
                <label for="comment" style="font-family: monospace; font-weight: bold; font-size: large;">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="10" class="form-control"></textarea>
                </br>

                <label for="rating" style="font-weight: bold; font-family: monospace; font-size: large;">Rating</label>            
                <input type="number" name="rating" min="0" max="10" value="0" step="0.5">

                </br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    </br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
                <div class="card">
                    <div class="card-body" style="background-color: #f5eeee;">
                        <div class="row">
                            <div class="col-md-3" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user %}
                                    <a href="{% url 'main:editreview' project_id review_id %}">Edit</a>
                                    <a href="{% url 'main:deletereview' project_id review_id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                                {% endif %}
                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                </br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="card" style="padding: 20px;">
            <div class="card-content">
                <h3 class="text-center">Edit Review</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                        {% if error %}
                            <strong style="color: red;">{{ error }}</strong>
                            </br>
                        {% endif %}
                    <input type="submit" value="Save Changes" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="container">
        </br>
        <div class="card" id="backdrop">
            <div class="card-body">
                <div class="row">
                    {% for project in projects %}
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="text-center">
                                    {% if project.image %} 
                                        <a href="#"><img src="{{ project.image.url }}" alt="{{ project.name }} image" width="100%" height="100%"></a>
                                    {% endif %}
                                    </br>
                                    <h3 class="text-center" style="font-family: monospace; font-weight: bold; color: crimson;">
                                        {{ project.name }}</h3>
                                    </br>
                                    <a href="{% url 'main:detail' project.id %}" class="btn btn-sm btn-outline-secondary" style="font-family: monospace; font-size: medium; font-weight: bold;">Review</a>
                                    </br>
                                    <small>Posted on: <i style="font-family: sans-serif; font-size: small; font-weight: bold;">{{ project.reviewDate }}</i></small>
                                </div>
                            </div>
                        </div>
                        </br>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}